// ISO 3166-1 alpha-2 codes, used by flag-icons (`fi fi-<code>`).
// Add an entry here when swapping to a tournament with different teams.
const TEAM_COUNTRY_CODE: Record<string, string> = {
  Vietnam: 'vn',
  Singapore: 'sg',
  Indonesia: 'id',
  Cambodia: 'kh',
  'Timor-Leste': 'tl',
  Thailand: 'th',
  Malaysia: 'my',
  Philippines: 'ph',
  Myanmar: 'mm',
  Laos: 'la',
  Algeria: 'dz',
  Brunei: 'bn',
  Argentina: 'ar',
  Australia: 'au',
  Bahrain: 'bh',
  Belgium: 'be',
  Brazil: 'br',
  Cameroon: 'cm',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  'Costa Rica': 'cr',
  Croatia: 'hr',
  Cuba: 'cu',
  Denmark: 'dk',
  Ecuador: 'ec',
  Egypt: 'eg',
  Fiji: 'fj',
  France: 'fr',
  Greece: 'gr',
  Haiti: 'ht',
  Honduras: 'hn',
  'Hong Kong': 'hk',
  India: 'in',
  Iran: 'ir',
  Iraq: 'iq',
  Italy: 'it',
  'Ivory Coast': 'ci',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kuwait: 'kw',
  Kyrgyzstan: 'kg',
  Mali: 'ml',
  Mexico: 'mx',
  Montenegro: 'me',
  Morocco: 'ma',
  Mozambique: 'mz',
  'New Caledonia': 'nc',
  'New Zealand': 'nz',
  'North Korea': 'kp',
  Oman: 'om',
  Panama: 'pa',
  Pakistan: 'pk',
  Palestine: 'ps',
  Qatar: 'qa',
  'Republic of Ireland': 'ie',
  Romania: 'ro',
  'Saudi Arabia': 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  'South Korea': 'kr',
  Spain: 'es',
  Syria: 'sy',
  Tajikistan: 'tj',
  Tanzania: 'tz',
  Uganda: 'ug',
  'United Arab Emirates': 'ae',
  'United States': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Venezuela: 've',
  Yemen: 'ye',
};

export function countryCodeFor(team: string): string | null {
  return TEAM_COUNTRY_CODE[team] ?? null;
}
